# Generated by Django 2.0.2 on 2018-05-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180506_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
    ]
