# Generated by Django 2.0.2 on 2018-05-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180506_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email_validated',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='activation_key',
        ),
    ]
